version: '3.7'

services:

  db:
    build:
      context: .
      dockerfile: mysql-dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%%
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=database
    volumes:
      - database-data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: fastapi-dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_HOSTS=db:3306
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=database
    volumes:
      - images-data:/usr/src/app/public/images

volumes:
  database-data:
  images-data:
